name: desafio_estante_de_livros
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Modular
  flutter_modular: ^5.0.3
  modular_bloc_bind: ^1.0.1

  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # General
  equatable: ^2.0.5
  intl: ^0.18.0
  asuka: ^2.2.1
  vocsy_epub_viewer: ^3.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  http: ^1.1.2
  cached_network_image: ^3.3.0
  permission_handler: ^11.1.0
  path_provider: ^2.1.1
  dio: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  #General
  sqflite_common_ffi: ^2.3.0+4
  flutter_lints: ^2.0.0

  #Tests
  mockito: ^5.4.3
  build_runner: ^2.4.7

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#1B9DFF"
  image: assets/images/app_icon.png
  android_12:
    image: assets/images/android_12.png
    color: "#1B9DFF"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
